### ISSUE TITLE
Dirname isn't defined

### ISSUE THREAD

**Issue by Mogeiman** [luislealdev/Inventory-App-Nextron#7]
I cloned this project and I am getting the following error when I tried running it on my local machine. `__dirname isn't defined`.

**Comment by luislealdev** [comment]
> I cloned this project and I am getting the following error when I tried running it on my local machine. `__dirname isn't defined`.

Hey! Have you install electron and all yarn packages? (Also please check the repo description). In case this error persist, check out [https://github.com/electron/electron/issues/24005](https://github.com/electron/electron/issues/24005)

This code is working for all the project developers, but you can answer this comment again if there seems not to be a solution and we'll review the code. ;)

**Comment by Mogeiman** [comment]
a bit more probing and it is working now. Thanks for the reply, I will close the issue now.
